---

- name: Enable Hosting queued Aegir module
  shell: drush --yes @hostmaster en hosting_queued
  become: yes
  become_user: aegir
  environment:
    PATH: "{{ aegir_drush_path }}:{{ ansible_env.PATH }}"
  changed_when: false # This will never report 'changed' status. But it will report 'ok', 'unreachable' or 'failed'

- name: Copy the service template
  template:
    src: hosting-queued.service.tpl
    dest: /etc/systemd/system/hosting-queued.service
    owner: root
    group: root
    mode: 0755

- name: Setup and start hosting-queued
  service:
    name: hosting-queued
    enabled: yes
    state: started
